lib/vote_web/router.ex
defmodule VoteWeb.Router do
  use VoteWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :put_root_layout, {VoteWeb.LayoutView, :root}
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :guardian do
    plug VoteWeb.Authentication.Pipeline
  end

  pipeline :browser_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  scope "/", VoteWeb do
    pipe_through [:browser, :guardian]

    get "/", HomepageController, :index
    get "/pick-user/:ballot", PublicUserController, :index
    post "/pick-user/:ballot", PublicUserController, :assign

    post   "/login",           AuthController, :login
    post   "/register",        AuthController, :register
    get    "/register/verify", AuthController, :verify_email
    delete "/logout",          AuthController, :logout

    live "/b/:ballot", BallotLive, :index
    live "/b/:ballot/results", ResultsLive, :index
  end

  scope "/auth", VoteWeb do
    pipe_through [:browser, :guardian]

    get "/:provider",          AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end

  scope "/", VoteWeb do
    pipe_through [:browser, :guardian, :browser_auth]

    live "/app", PageLive, :index
    live "/new", NewPollLive, :index
    live "/edit/:ballot", NewPollLive, :edit
  end

  # Other scopes may use custom stacks.
  # scope "/api", VoteWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  # if Mix.env() in [:dev, :test] do
  #   import Phoenix.LiveDashboard.Router

  #   scope "/" do
  #     pipe_through :browser
  #     live_dashboard "/dashboard", metrics: VoteWeb.Telemetry
  #   end
  # end
end

lib/vote_web/controllers/auth_controller.ex
defmodule VoteWeb.AuthController do
  use VoteWeb, :controller
  plug Ueberauth

  alias Vote.Accounts
  alias Vote.Token
  alias Vote.Email
  alias VoteWeb.Authentication
  alias VoteWeb.HomepageController

  def login(conn, %{"account" => %{"email" => email, "password" => pass}}) do
    case email |> Accounts.by_email() |> Authentication.authenticate(pass) do
      {:ok, account} ->
        redirect =
          case get_session(conn, :login_redirect) do
            nil -> Routes.homepage_path(conn, :index)
            val -> val
          end

        conn
        |> put_session(:login_redirect, nil)
        |> Authentication.log_in(account)
        |> redirect(to: redirect)

      {:error, :not_verified} ->
        conn
        |> put_flash(:error, "You must verify your email before logging in!")
        |> redirect(to: Routes.homepage_path(conn, :index))

      {:error, :invalid_credentials} ->
        conn
        |> put_flash(:error, "Incorrect email or password.")
        |> redirect(to: Routes.homepage_path(conn, :index))
    end
  end

  def callback(%{assigns: %{ueberauth_failure: _}} = conn, _params) do
    conn
    |> put_flash(:error, "Authentication failed.")
    |> redirect(to: Routes.homepage_path(conn, :index))
  end

  def callback(%{assigns: %{ueberauth_auth: auth}} = conn, _params) do
    case Accounts.get_or_register(auth) do
      {:ok, account} ->
        conn
        |> Authentication.log_in(account)
        |> redirect(to: Routes.page_path(conn, :index))

      {:error, _error_changeset} ->
        conn
        |> put_flash(:error, "Authentication failed.")
        |> redirect(to: Routes.homepage_path(conn, :index))
    end
  end

  def logout(conn, _params) do
    conn
    |> Authentication.log_out()
    |> redirect(to: Routes.homepage_path(conn, :index))
  end

  def register(%{assigns: %{ueberauth_auth: %{provider: :identity} = auth}} = conn, _) do
    case Accounts.register(auth) do
      {:ok, account} ->
        # generate an email verification token
        token = Token.generate_new_account_token(account)
        # generate the link to send in the email, pointing to our verify route
        verification_url = Routes.auth_url(conn, :verify_email, token: token)
        # send email
        Email.send_account_verification_email(account, verification_url)
        # get the domain of their email to have a nice link on the confirm page
        domain = account.email |> String.split("@") |> List.last()
        # render the page asking a user to check their email
        render(conn, :confirm, email: account.email, domain: domain)

      {:error, changeset} ->
        conn
        |> assign(:register_cs, changeset)
        |> HomepageController.index(%{})
    end
  end

  def verify_email(conn, %{"token" => token}) do
    with {:ok, id} <- Token.verify_new_account_token(token),
         {:ok,  _} <- Accounts.mark_verified(id) do
      conn
      |> put_flash(:info, "Email successfully verified! Please log in.")
      |> redirect(to: Routes.homepage_path(conn, :index))
    else
      _ -> conn
      |> put_flash(:error, "The verification token is invalid or has already been used.")
      |> redirect(to: Routes.homepage_path(conn, :index))
    end
  end

  def verify_email(conn, _) do
    conn
    |> put_flash(:error, "No verification token found in URL.")
    |> redirect(to: Routes.homepage_path(conn, :index))
  end
end

lib/vote_web/controllers/homepage_controller.ex
defmodule VoteWeb.HomepageController do
  alias Vote.Accounts.Account
  use VoteWeb, :controller

  @account_cs Account.unverified_changeset(%Account{}, %{})

  def index(conn, params) do
    if conn.assigns[:account] do
      redirect(conn, to: Routes.page_path(conn, :index))
    else
      conn
      |> put_login_redir(params)
      |> render(:index,
        page_title: "Login",
        login: Routes.auth_path(conn, :login),
        login_cs: Map.get(conn.assigns, :login_cs, @account_cs),
        register: Routes.auth_path(conn, :register),
        register_cs: Map.get(conn.assigns, :register_cs, @account_cs)
      )
    end
  end

  def put_login_redir(conn, %{"cb" => path}) do
    put_session(conn, :login_redirect, path)
  end
  def put_login_redir(conn, _params), do: conn
end

lib/vote_web/controllers/public_user_controller.ex
defmodule VoteWeb.PublicUserController do
  use VoteWeb, :controller

  defmodule UserSchema do
    use Ecto.Schema
    import Ecto.Changeset

    schema "user" do
      field :name, :string, virtual: true
    end

    def changeset(model, params) do
      model
      |> cast(params, [:name])
      |> validate_required([:name])
      |> validate_length(:name, min: 3)
      |> Map.put(:action, :insert)
    end

    def change(params \\ %{}) do
      changeset(%UserSchema{}, params)
    end
  end

  def index(conn, %{"ballot" => slug}) do
    case get_session(conn, :public_user) do
      nil -> render(conn, :index, cs: UserSchema.change(), slug: slug)
      _el -> redirect(conn, to: Routes.ballot_path(conn, :index, slug))
    end
  end

  def assign(conn, %{"pick_user" => params, "ballot" => slug}) do
    case UserSchema.change(params) do
      %Ecto.Changeset{errors: [_ | _]} = cs ->
        render(conn, :index, cs: cs, slug: slug)
      cs ->
        conn
        |> put_session(:public_user, Ecto.Changeset.get_field(cs, :name))
        |> redirect(to: Routes.ballot_path(conn, :index, slug))
    end
  end
end

lib/vote_web/live/ballot_live.ex
defmodule VoteWeb.BallotLive do
  use VoteWeb, :live_view
  alias Phoenix.PubSub
  alias Vote.Ballots
  alias Vote.Ballots.LiveState
  alias Vote.Ballots.ResponseSet
  alias Vote.Voting

  def load_ballot(socket, nil) do
    socket
    |> put_flash(:error, "Invalid ballot link.")
    |> redirect(to: Routes.homepage_path(socket, :index))
  end

  def load_ballot(socket, ballot) do
    LiveState.register(ballot.id)
    PubSub.subscribe(Vote.PubSub, "ballot/#{ballot.id}/update")
    socket
    |> assign(ballot: ballot)
    |> assign(page_title: ballot.title)
    |> update_cs(%{})
  end

  @impl true
  def mount(%{"ballot" => slug}, session, socket) do
    ballot = Ballots.by_slug(slug)
    account = VoteWeb.Authentication.load_user(session)

    case {account, session, ballot} do
      {_, _, %Ballots.Ballot{closed: true}} ->
        socket
        |> close_redir(slug)
        |> ok()
      {{:ok, user}, _, _} ->
        socket
        |> assign(user: user.id)
        |> load_ballot(ballot)
        |> ok()
      {{:error, _}, %{"public_user" => user}, %Ballots.Ballot{public: true}} ->
        socket
        |> assign(user: user)
        |> load_ballot(ballot)
        |> ok()
      {{:error, _}, _no_public_user, %Ballots.Ballot{public: true}} ->
        socket
        |> redirect(to: Routes.public_user_path(socket, :index, slug))
        |> ok()
      {{:error, _}, _, _} ->
        curr_path = Routes.ballot_path(socket, :index, slug)
        socket
        |> put_flash(:error, "Please log in first! (Authentication Error)")
        |> redirect(to: Routes.homepage_path(socket, :index, cb: curr_path) <> "#login")
        |> ok()
    end
  end

  @impl true
  def handle_event("vote", %{"response_set" => params}, socket) do
    socket
    |> update_cs(params)
    |> save_cs()
    |> noreply()
  end

  @impl true
  def handle_event("publish_ballot", _params, socket) do
    if socket.assigns.user == socket.assigns.ballot.account_id do
      {:ok, ballot} = Ballots.publish(socket.assigns.ballot)
      socket
      |> put_flash(:info, "Ballot published successfully!")
      |> redirect(to: Routes.ballot_path(socket, :index, ballot.slug))
      |> noreply()
    else
      noreply(socket)
    end
  end

  @impl true
  def handle_event("add_option", %{"option" => option, "idx" => idx}, socket) do
    idx = String.to_integer(idx)
    item_id = Enum.at(socket.assigns.ballot.ballot_items, idx).id
    option = String.trim(option)

    socket
    |> broadcast_listener({:add_option, item_id, option})
    |> noreply()
  end

  @impl true
  def handle_info(:ballot_updated, socket) do
    socket
    |> assign(ballot: Ballots.by_slug(socket.assigns.ballot.slug))
    |> noreply()
  end

  @impl true
  def handle_info(:ballot_deleted, socket) do
    socket
    |> put_flash(:error, "Ballot was deleted.")
    |> redirect(to: Routes.homepage_path(socket, :index))
    |> noreply()
  end

  @impl true
  def handle_info(:ballot_closed, socket) do
    close_redir(socket, socket.assigns.ballot.slug) |> noreply()
  end

  def update_cs(socket, params) do
    # update to new ballot in case it was changed
    ballot = Ballots.by_slug(socket.assigns.ballot.slug)
    # get the current user from the socket
    user = socket.assigns.user
    # get the yet-to-be edited response set
    response_set = ResponseSet.find(user, ballot.id)
    # make a new change set from these
    assign(socket, cs: ResponseSet.changeset(response_set, params, ballot, user))
  end

  def save_cs(socket) do
    ballot = socket.assigns.ballot
    cond do
      ballot.draft -> socket
      ballot.closed -> socket |> close_redir(ballot.slug)
      true ->
        ResponseSet.save(socket.assigns.cs)
        PubSub.broadcast(Vote.PubSub, "ballot/#{ballot.id}/vote", :ballot_vote)
        socket
    end
  end

  def close_redir(socket, slug) do
    socket
    |> put_flash(:info, "Voting has closed.")
    |> redirect(to: Routes.results_path(socket, :index, slug))
  end

  def broadcast_listener(socket, data) do
    id = socket.assigns.ballot.id
    PubSub.broadcast(Vote.PubSub, "ballot/#{id}/listener", data)
    socket
  end

  def voting_input(method, form, field, options, opts) do
    Voting.input(method, form, field, options, opts)
  end
end

lib/vote_web/live/new_poll_live.ex
defmodule VoteWeb.NewPollLive do
  import Ecto.Changeset
  use VoteWeb, :live_view
  alias Phoenix.PubSub
  alias Vote.Ballots
  alias Vote.Voting

  # TODO: when someone is redirected to the ballot view after saving
  # and then wants to edit, they go back in history to the /new page
  # make it so they instead go back and edit the ballot in /edit/:id

  @impl true
  def mount(%{"ballot" => slug}, session, socket) do
    {:ok, user} = VoteWeb.Authentication.load_user(session)
    ballot = Ballots.by_slug(slug)

    cond do
      is_nil(ballot) ->
        socket
        |> put_flash(:error, "Invalid ballot link.")
        |> redirect(to: Routes.homepage_path(socket, :index))
        |> ok()

      ballot.account_id != user.id ->
        socket
        |> put_flash(:error, "Only ballot authors can edit their ballot.")
        |> redirect(to: Routes.homepage_path(socket, :index))
        |> ok()

      true ->
        PubSub.subscribe(Vote.PubSub, "ballot/#{ballot.id}/update")

        socket
        |> assign(ballot: ballot)
        |> update_ballot()
        |> assign(page_title: "Edit " <> ballot.title)
        |> assign(account: user)
        |> ok()
    end
  end

  @impl true
  def mount(_params, session, socket) do
    {:ok, user} = VoteWeb.Authentication.load_user(session)
    socket
    |> assign(ballot: nil)
    |> update_ballot()
    |> assign(page_title: "New Ballot")
    |> assign(account: user)
    |> ok()
  end

  @impl true
  def handle_info(:ballot_updated, socket) do
    socket
    |> update_ballot()
    |> noreply()
  end

  @impl true
  def handle_info(:ballot_closed, socket) do
    slug = socket.assigns.ballot.slug
    socket
    |> put_flash(:error, "Ballot was closed.")
    |> redirect(to: Routes.results_path(socket, :index, slug))
    |> noreply()
  end

  @impl true
  def handle_info(:ballot_deleted, socket) do
    socket
    |> put_flash(:error, "Ballot was deleted.")
    |> redirect(to: Routes.homepage_path(socket, :index))
    |> noreply()
  end

  @impl true
  def handle_event("validate", %{"ballot" => ballot}, socket) do
    socket
    |> update_ballot(ballot)
    |> noreply()
  end

  @impl true
  def handle_event("save", %{"ballot" => params}, socket) do
    case Ballots.save(socket.assigns.ballot, params, socket.assigns.account) do
      {:error, %Ecto.Changeset{} = cs} ->
        socket
        |> assign(cs: cs)
        |> noreply()

      {:ok, ballot} ->
        socket
        |> put_flash(:info, "Draft saved successfully!")
        |> push_redirect(to: Routes.ballot_path(socket, :index, ballot.slug))
        |> noreply()
    end
  end

  @impl true
  def handle_event("push_ballot_item", _, socket) do
    socket
    |> assign(cs: Ballots.push_item(socket.assigns.cs))
    |> noreply()
  end

  def handle_event("delete_ballot_item", %{"idx" => idx}, socket) do
    socket
    |> assign(cs: Ballots.delete_item(socket.assigns.cs, String.to_integer(idx)))
    |> noreply()
  end

  def handle_event("delete_option", %{"idx" => idx, "item" => item}, socket) do
    idx = String.to_integer(idx)
    item = String.to_integer(item)

    socket
    |> assign(cs: Ballots.delete_option(socket.assigns.cs, item, idx))
    |> noreply()
  end

  def update_ballot(socket, params \\ %{}) do
    assign(socket, cs: Ballots.new(socket.assigns.ballot, params))
  end

  def data_or_cs(%Ecto.Changeset{} = cs, key), do: get_field(cs, key)
  def data_or_cs(data, key), do: Map.get(data, key)

  def voting_methods(), do: Voting.methods
end

lib/vote_web/live/page_live.ex
defmodule VoteWeb.PageLive do
  use VoteWeb, :live_view
  alias Phoenix.PubSub
  alias VoteWeb.Authentication
  alias Vote.Ballots
  alias Vote.Ballots.ResponseSet

  @impl true
  def mount(_params, session, socket) do
    {:ok, user} = Authentication.load_user(session)

    socket
    |> assign(account: user)
    |> assign(page_title: "Home")
    |> update(user)
    |> ok()
  end

  @impl true
  def handle_event("delete_modal", %{"idx" => idx}, socket) do
    params = %{
      title: "Delete Ballot?",
      desc: :delete,
      ok_click: "delete",
      ok_data: idx,
    }
    socket
    |> assign(modal: params)
    |> noreply()
  end

  @impl true
  def handle_event("close_modal", %{"idx" => idx}, socket) do
    params = %{
      title: "Close Voting?",
      desc: :close,
      ok_click: "close",
      ok_data: idx,
    }
    socket
    |> assign(modal: params)
    |> noreply()
  end

  @impl true
  def handle_event("hide_modal", _params, socket) do
    socket
    |> assign(modal: nil)
    |> noreply()
  end

  @impl true
  def handle_event("delete", %{"data" => idx}, socket) do
    {:ok, ballot} = socket.assigns.my_ballots
    |> Enum.at(String.to_integer(idx))
    |> Ballots.delete()

    topic = "ballot/#{ballot.id}/update"
    PubSub.broadcast(Vote.PubSub, topic, :ballot_deleted)

    socket
    |> update(socket.assigns.account)
    |> assign(modal: nil)
    |> noreply()
  end

  # TODO: prevent data base inserts for closed ballots

  @impl true
  def handle_event("close", %{"data" => idx}, socket) do
    {:ok, ballot} = socket.assigns.my_ballots
    |> Enum.at(String.to_integer(idx))
    |> Ballots.close()

    topic = "ballot/#{ballot.id}/update"
    PubSub.broadcast(Vote.PubSub, topic, :ballot_closed)

    socket
    |> update(socket.assigns.account)
    |> assign(modal: nil)
    |> noreply()
  end

  def update(socket, user) do
    socket
    |> assign(my_ballots: Ballots.authored_by_user(user))
    |> assign(voted_ballots: ResponseSet.find_ballots(user.id))
  end
end

lib/vote_web/views/auth_view.ex
defmodule VoteWeb.AuthView do
  use VoteWeb, :view
  alias VoteWeb.HomepageView

  def render("index.html", assigns) do
    HomepageView.render("index.html", assigns)
  end
end

lib/vote_web/views/homepage_view.ex
defmodule VoteWeb.HomepageView do
  use VoteWeb, :view
  alias Vote.Voting

  def voting_methods(), do: Voting.method_links
end

lib/vote_web/views/layout_view.ex
defmodule VoteWeb.LayoutView do
  use VoteWeb, :view
end

lib/vote_web/live/ballot_live.html.leex
<div class="container ballot-view">
  <%= form_for @cs, "#", [phx_submit: :vote, phx_change: :vote], fn f -> %>
    <div class="row">
      <h1 class="<%= if @ballot.desc do "" else "mb0" end %>">
        <%= if @ballot.draft do %>
          <span style="opacity:0.7;">Draft Preview for</span>
          <i><%= @ballot.title %></i>
        <% else %>
          <%= @ballot.title %>
        <% end %>
      </h1>
    </div>
    <%= if @ballot.draft do %>
      <div class="row">
        <blockquote style="color:darkred;font-weight:bold;">
          NOTE: this is a draft, no votes here will be counted!
          <br/>
          Publish this ballot by clicking 'Publish Ballot' at the bottom.
        </blockquote>
      </div>
    <% end %>
    <%= if @ballot.desc do %>
      <div class="row">
        <div class="ballot-desc">
          <%= render_markdown(@ballot.desc) %>
        </div>
      </div>
    <% end %>

    <%= inputs_for f, :responses, fn p -> %>
      <% idx = p.index %>
      <% item = Enum.at(@ballot.ballot_items, idx) %>
      <hr/>
      <%= if length(@ballot.ballot_items) > 1 do %>
        <div class="row">
          <h2><%= idx + 1 %>. <%= item.title %></h2>
        </div>
        <%= if item.desc do %>
          <div class="row">
            <div class="ballot-item-desc">
              <%= render_markdown(item.desc) %>
            </div>
          </div>
        <% end %>
      <% end %>
      <div class="row">
        <% opts = [item_idx: idx] %>
        <%= voting_input(item.voting_method, p, :response, item, opts) %>
      </div>
      <%= if item.appendable and !@ballot.draft do %>
        <div class="row mb0"
             id="add_option_<%= idx %>"
             phx-hook="AppendToItem"
        >
          <%= text_input p, :append, [
              class: "add_option mr1 mb1",
              placeholder: "Add your own options to vote on",
              data_idx: idx,
          ] %>
          <button>add</button>
        </div>
      <% end %>
    <% end %>
    <hr/>
    <% res = Routes.results_url(@socket, :index, @ballot.slug) %>
    <div class="row fl-baseline">
      <%= if @ballot.draft do %>
        <%= if @ballot.account_id == @user do %>
          <div class="row">
            <a class="column button button-outline mr1"
               href="<%= Routes.new_poll_url(@socket, :edit, @ballot.slug) %>"
            >back to editing</a>
            <a phx-click="publish_ballot" class="column button">publish ballot</a>
            <div class="column"></div>
            <div class="column"></div>
          </div>
        <% else %>
          <p><i>Only the ballot's author can publish ballots.</i></p>
        <% end %>
      <% else %>
        <a href="<%= res %>" class="mr1 button">view results</a>
        <p><i>
          (your vote is saved automatically)
        </i></p>
      <% end %>
    </div>
  <% end %>
</div>

lib/vote_web/live/page_live.html.leex
<div class="container">
  <div class="row"> <h2>Ballots You've Voted On</h2> </div>
  <div class="row">
    <table>
      <tr>
        <th class="w100">Title</th>
        <th></th>
        <th></th>
      </tr>
      <%= for ballot <- Enum.reject(@voted_ballots, &(&1.draft)) do %>
        <% vote = Routes.ballot_url(@socket, :index, ballot.slug) %>
        <% results = Routes.results_url(@socket, :index, ballot.slug) %>
        <tr>
          <td class="w100">
            <%= ballot.title %>
          </td>
          <td>
            <a href="<%= vote %>">Vote</a>
          </td>
          <td>
            <a href="<%= results %>">Results</a>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
  <div class="row"> <hr/> </div>
  <div class="row"> <h2>Ballots You've Made</h2> </div>
  <div class="row">
    <table>
      <tr>
        <th class="w100">Title</th>
        <th></th> <th></th> <th></th> <th></th> <th></th>
      </tr>
      <%= for {ballot, idx} <- Enum.with_index(@my_ballots) do %>
        <% edit = Routes.new_poll_url(@socket, :edit, ballot.slug) %>
        <% vote = Routes.ballot_url(@socket, :index, ballot.slug) %>
        <% results = Routes.results_url(@socket, :index, ballot.slug) %>
        <tr>
          <td class="w100">
            <%= ballot.title %>
          </td>
          <td style="text-align:center;">
              <%= cond do %>
              <% ballot.draft -> %> <i>Draft</i>
              <% ballot.closed -> %> <i>Closed</i>
              <% true -> %> <i>Open</i>
              <% end %>
          </td>
          <td>
              <%= if not ballot.draft and not ballot.closed do %>
              <a href="#" phx-click="close_modal" phx-value-idx="<%= idx %>">Close</a>
              <% end %>
          </td>
          <td>
            <%= cond do %>
              <% ballot.draft -> %> <a href="<%= edit %>">Edit</a>
              <% ballot.closed -> %>
              <% true -> %> <a href="<%= vote %>">Vote</a>
            <% end %>
          </td>
          <td>
            <%= if ballot.draft do %>
              <a href="<%= vote %>">Preview</a>
            <% else %>
              <a href="<%= results %>">Results</a>
            <% end %>
          </td>
          <td>
            <a href="#" phx-click="delete_modal" phx-value-idx="<%= idx %>">Delete</a>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
  <div class="row">
    <a href="<%= Routes.new_poll_path(@socket, :index) %>" class="button">
      new ballot
    </a>
  </div>
</div>

<%= if assigns[:modal] do %>
  <div class="modal-container">
    <div class="modal-content">
      <a href="#" phx-click="hide_modal"
         class="btn-close closemodal">&times;</a>

      <div class="modal-header"><h2><%= @modal.title %></h2></div>

      <p>
        <%= if @modal.desc == :delete do %>
          Are you sure you want to delete this ballot?
          <br/>
          This <b>cannot</b> be undone.
        <% end %>
        <%= if @modal.desc == :close do %>
          This will prevent anyone from casting or changing their votes.
          <br/>
          This <b>cannot</b> be undone.
        <% end %>
      </p>

      <div class="row modal-controls">
        <div class="column"></div>
        <div class="column"></div>
        <a href="#" phx-click="hide_modal"
           class="column button button-outline">No</a>
        <a href="#" class="column button button"
           phx-click="<%= @modal.ok_click %>"
           phx-value-data="<%= @modal.ok_data %>"
        >Yes</a>
      </div>
    </div>
  </div>
<% end %>